Hyodrogen Horizons initial updates
the-orange-alliance/project-ems pull request #66
Opened 2023-08-30 18:39 UTC by kyle-flynn

Provides foundational work to enable work on Hydrogen Horizons FGC 2023 game. There is still a good amount of UI work that needs to be done, but this should allow you to start work on the field control system.

2023-08-30 18:40 UTC, scarabaeus approved these changes
APPROVED -- LOOKS GREAT!

2023-08-30 19:49 UTC, NoahAndrews commented
![image](https://github.com/the-orange-alliance/project-ems/assets/10224994/92db82d6-bd40-4189-8522-b560fcf41cd9)

Might want to cut down on the all-caps, haha

2023-08-30 23:53 UTC, NoahAndrews requested changes

2023-08-31 16:42 UTC, NoahAndrews commented on lib/models/src/seasons/HydrogenHorizons.ts
> +  redAlignment: number;
Disregard, added to #69

2023-08-31 16:43 UTC, NoahAndrews approved these changes
Approving this PR for merging as-is. I've made some improvements in #69, but they can be merged separately.

2023-08-31 18:51 UTC, merged