Settings page update and several other fixes
the-orange-alliance/project-ems pull request #77
Opened 2023-09-09 00:17 UTC by kyle-flynn

Address #76

2023-09-11 16:15 UTC, NoahAndrews requested changes
Rather than using terms like "Motor One Open Position" and "Motor One Close Position", let's use "Red servo holding pulse width" and "Red servo released pulse width" (with adjusted settings names to match)

2023-09-11 16:15 UTC, NoahAndrews commented on front-end/src/seasons/HydrogenHorizons/Settings.tsx
> +    motorOneOpenPositionAtom
Should be `motorTwoOpenPositionAtom`

2023-09-11 16:15 UTC, NoahAndrews commented on front-end/src/seasons/HydrogenHorizons/Settings.tsx
> +    motorOneClosePositionAtom
Should be `motorTwoClosePositionAtom`

2023-09-20 17:56 UTC, kyle-flynn commented
@NoahAndrews can you please re-review I've fixed the errors.

2023-09-20 18:07 UTC, NoahAndrews approved these changes
I'd also requested some renaming, but sure, we can go with this.

2023-09-22 16:21 UTC, merged